# Generated by Django 3.2.3 on 2021-05-20 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('login', models.CharField(max_length=40)),
                ('mdp', models.CharField(max_length=30)),
                ('type_compte', models.CharField(choices=[('D', 'D'), ('E', 'E')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(default='SOME STRING', max_length=100)),
                ('prenom', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('date_inscription', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 154903))),
                ('date_naissance', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 154903))),
                ('wilaya_naissance', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('classement_concours', models.IntegerField(default=1)),
                ('annee_etude', models.IntegerField(default=1)),
                ('inscrit', models.BooleanField(default=False)),
                ('reinscrit', models.BooleanField(default=False)),
                ('delibere', models.BooleanField(default=False)),
                ('date_deliberation', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 154903))),
                ('date_reinscription', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 154903))),
                ('nom_lab', models.CharField(choices=[('MCS', 'MCS'), ('LCSI', 'LCSI')], max_length=20)),
                ('compte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 155897))),
                ('sexe', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('nom_lab', models.CharField(choices=[('MCS', 'MCS'), ('LCSI', 'LCSI')], max_length=20)),
                ('compte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.IntegerField(default=0)),
                ('date_eval', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 159888))),
                ('etudiant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.FileField(max_length=254, upload_to='uploads/')),
                ('type_piece', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'EXCEL'), ('IMAGE', 'IMAGE'), ('LIEN', 'LIEN')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CS', 'CS'), ('CFD', 'CFD'), ('JURY', 'JURY'), ('PROF', 'PROF'), ('DT', 'DT'), ('ADPGR', 'ADPGR'), ('DAPGR', 'DAPGR')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('valide_cfd', models.BooleanField(default=False)),
                ('prise', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('doctorant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('dt', models.ManyToManyField(to='gestion_FD.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reun', models.DateField()),
                ('heure', models.DateTimeField()),
                ('descriptif', models.TextField()),
                ('doctorant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('dt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.employe')),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pv', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 161849))),
                ('piece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.piecejointe')),
                ('redacteur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('etudiants', models.ManyToManyField(to='gestion_FD.Doctorant')),
                ('evaluation', models.ManyToManyField(to='gestion_FD.Eval_module')),
                ('prof', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Fiche_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eval', models.DateField(default=datetime.datetime(2021, 5, 20, 11, 53, 40, 157895))),
                ('valide', models.BooleanField(default=False)),
                ('doctorant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.piecejointe')),
                ('jury', models.ManyToManyField(to='gestion_FD.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Etat_avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_etat_avancement', models.DateField()),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.piecejointe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='role',
            field=models.ManyToManyField(to='gestion_FD.Role'),
        ),
        migrations.CreateModel(
            name='Dossier_Doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.ManyToManyField(to='gestion_FD.PieceJointe')),
            ],
        ),
        migrations.AddField(
            model_name='doctorant',
            name='dossier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.dossier_doctorant'),
        ),
    ]
