# Generated by Django 3.2 on 2021-05-30 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_FD', '0007_auto_20210529_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='date_deliberation',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='eval_module',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 731310)),
        ),
        migrations.AlterField(
            model_name='fiche_evaluation',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685)),
        ),
        migrations.AlterField(
            model_name='pv',
            name='date_pv',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 731310)),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pres', models.DateField(default=datetime.datetime(2021, 5, 30, 18, 21, 26, 715685))),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('doctorant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('jury', models.ManyToManyField(to='gestion_FD.Employe')),
            ],
        ),
    ]
