# Generated by Django 3.2.3 on 2021-05-27 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_FD', '0007_auto_20210527_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='date_deliberation',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 389527)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 389527)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 389527)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 389527)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 390522)),
        ),
        migrations.AlterField(
            model_name='eval_module',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 395476)),
        ),
        migrations.AlterField(
            model_name='fiche_evaluation',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 393513)),
        ),
        migrations.AlterField(
            model_name='pv',
            name='date_pv',
            field=models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 396512)),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pres', models.DateField(default=datetime.datetime(2021, 5, 27, 20, 25, 33, 392516))),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('doctorant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.doctorant')),
                ('jury', models.ManyToManyField(to='gestion_FD.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='fiche_evaluation',
            name='Presentation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.presentation'),
        ),
    ]
