# Generated by Django 3.2.3 on 2021-06-04 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_FD', '0024_auto_20210604_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='Bourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_FD.bourse'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_deliberation',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 452774)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 452774)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 452774)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 452774)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='reinscription',
            field=models.ManyToManyField(blank=True, null=True, to='gestion_FD.Reinscription'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 449782)),
        ),
        migrations.AlterField(
            model_name='eval_module',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 458758)),
        ),
        migrations.AlterField(
            model_name='fiche_evaluation',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 455766)),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='date_pres',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 454769)),
        ),
        migrations.AlterField(
            model_name='pv',
            name='date_pv',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 458758)),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 45, 56, 451777)),
        ),
    ]
