# Generated by Django 3.2.3 on 2021-06-08 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_FD', '0026_auto_20210604_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinscription',
            name='valide_cfd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reinscription',
            name='valide_cs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reinscription',
            name='valide_dt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_deliberation',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='eval_module',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='fiche_evaluation',
            name='date_eval',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='date_pres',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='pv',
            name='date_pv',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='date_reinscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 22, 41, 31, 316622)),
        ),
    ]
